
# This comment is added to re-trigger GitHub Actions workflow evaluation.
name: Send Daily Lunch Menu

on:
  schedule:
    # Runs at 00:30 UTC, which is 9:30 AM in Korea (KST)
    - cron: '30 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          API_KEY: ${{ secrets.NEIS_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          KAKAO_ACCESS_TOKEN: ${{ secrets.KAKAO_ACCESS_TOKEN }}
        run: |
          echo $API_KEY > api.txt
          echo $SLACK_WEBHOOK_URL > slack_webhook_url.txt
          echo $KAKAO_ACCESS_TOKEN > kakao_access_token.txt
          python main.py
